; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
extra_configs = settings.ini

[env:esp32-s3-devkitc-1]
build_type = debug
monitor_filters = esp32_exception_decoder
;platform = espressif32
platform = https://github.com/pioarduino/platform-espressif32/releases/download/54.03.20/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
build_flags =
  -DARDUINO_USB_CDC_ON_BOOT=0
  -DAPP_DEV_MODE=${joy.dev_mode}
  '-DAPP_AP_SSID="${joy.ap_ssid}"'
  '-DAPP_AP_PASSWORD="${joy.ap_password}"'
  -DAPP_AP_CHANNEL=${joy.ap_channel}
  -DAPP_AP_MAX_CLIENTS=${joy.ap_max_clients}
  '-DAPP_AP_IP="${joy.ap_ip}"'
  '-DAPP_AP_GATEWAY="${joy.ap_gateway}"'
  '-DAPP_AP_SUBNET="${joy.ap_subnet}"'
  '-DAPP_WIFI_SSID="${joy.wifi_ssid}"'
  '-DAPP_WIFI_PASSWORD="${joy.wifi_password}"'
  -DAPP_WIFI_CONNECT_TIMEOUT_MS=${joy.wifi_connect_timeout_ms}
  -DAPP_UI_POLL_MS=${joy.ui_poll_ms}
  -DAPP_ANALOG_INPUT_COUNT=${joy.analog_input_count}
  -DAPP_ANALOG_INPUT_1_PIN=${joy.analog_input_1_pin}
  -DAPP_ANALOG_INPUT_2_PIN=${joy.analog_input_2_pin}
  -DAPP_ANALOG_INPUT_3_PIN=${joy.analog_input_3_pin}
  -DAPP_ANALOG_INPUT_4_PIN=${joy.analog_input_4_pin}
  -DAPP_ANALOG_READ_INTERVAL_MS=${joy.analog_read_interval_ms}
  -DAPP_ANALOG_READ_RESOLUTION_BITS=${joy.analog_read_resolution_bits}
  -DAPP_ANALOG_SAMPLES_PER_READ=${joy.analog_samples_per_read}
  -DAPP_PPM_CHANNEL_COUNT=${joy.ppm_channel_count}
  -DAPP_PPM_OUTPUT_PIN=${joy.ppm_output_pin}
  -DAPP_PPM_FRAME_US=${joy.ppm_frame_us}
  -DAPP_PPM_PULSE_US=${joy.ppm_pulse_us}
  -DAPP_PPM_MIN_SYNC_US=${joy.ppm_min_sync_us}
  -DAPP_PPM_ACTIVE_LOW=${joy.ppm_active_low}
  -DAPP_STATUS_LED_ENABLED=${joy.status_led_enabled}
  -DAPP_STATUS_LED_PIN=${joy.status_led_pin}
  -DAPP_STATUS_LED_BRIGHTNESS=${joy.status_led_brightness}
